yummy:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: yummy_dash
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGaTx6qK9g2eEPZ1WLw
    access-key-secret: yatx0OObffH9n2UtNUVTGfklH0hCc9
    bucket-name: yummy-dash
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx1be6a7a0500ad449
    secret: 3eca6a471644b55bbb7943d1ba6cb935