server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${yummy.datasource.driver-class-name}
      url: jdbc:mysql://${yummy.datasource.host}:${yummy.datasource.port}/${yummy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${yummy.datasource.username}
      password: ${yummy.datasource.password}
  redis:
    host: ${yummy.redis.host}
    port: ${yummy.redis.port}
    password: ${yummy.redis.password}
    database: ${yummy.redis.database}

mybatis:
  #mapper config doc
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yummy.entity
  configuration:
    #enable field mapping
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      yummy:
        mapper: debug
        service: info
        controller: info

yummy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # user jwt properties
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${yummy.alioss.endpoint}
    access-key-id: ${yummy.alioss.access-key-id}
    access-key-secret: ${yummy.alioss.access-key-secret}
    bucket-name: ${yummy.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mchid : ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}